name: Fixed-Domain-Proxy
on:
  workflow_dispatch:
  repository_dispatch:
    types: [start_proxy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tools
        run: |
          sudo bash -s -- install < <(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)
          curl -L -o cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Config & Run
        env:
          CF_TOKEN: ${{ secrets.CF_TUNNEL_TOKEN }}
        run: |
          # 构造配置 (UUID可自定义)
          cat <<EOF > config.json
          {
            "inbounds": [{
              "port": 8080, "protocol": "vless",
              "settings": {"clients": [{"id": "d342d11e-d424-4583-b36e-52490062b323"}], "decryption": "none"},
              "streamSettings": {"network": "ws", "wsSettings": {"path": "/speedtest"}}
            }],
            "outbounds": [{"protocol": "freedom"}]
          }
          EOF
          
          # 启动服务
          sudo xray run -c config.json &
          sudo cloudflared tunnel run --token $CF_TOKEN
