name: VPN-Stop-Service

on:
  repository_dispatch:
    types: [stop_proxy]
  workflow_dispatch:

jobs:
  shutdown:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: false
          access_token: ${{ secrets.MY_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
