- name: Configure Xray
        run: |
          sudo systemctl stop xray || true
          cat <<EOF | sudo tee /usr/local/etc/xray/config.json
          {
              "inbounds": [{
                  "port": 8080,
                  "protocol": "vless",
                  "settings": {
                      "clients": [{"id": "d342d11e-d424-4583-b36e-52490062b323"}],
                      "decryption": "none"
                  },
                  "streamSettings": {
                      "network": "ws",
                      "wsSettings": {"path": "/speedtest"}
                  }
              }],
              "outbounds": [{"protocol": "freedom"}]
          }
          EOF
          sudo /usr/local/bin/xray run -c /usr/local/etc/xray/config.json &
